### ISSUE TITLE
Click on "Add instance" crash the application

### ISSUE THREAD

**Issue by kerphi** [Inist-CNRS/ezmaster#2]
Just before i installed the app from scratch folowing the README. I did a "Install and run (without docker)".

Here is my backtrace:
```
/home/kerphi/ezmaster/routes/route.js:176
      container.start(function (err, data) {
               ^

TypeError: Cannot read property 'start' of null
    at /home/kerphi/ezmaster/routes/route.js:176:16
    at /home/kerphi/ezmaster/node_modules/dockerode/lib/docker.js:37:21
    at /home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:235:7
    at getCause (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:257:7)
    at Modem.buildPayload (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

```

**Comment by kerphi** [comment]
I tested and clicking the button does not crash anymore the application but nothing appends 

I just got this in the debug logs:
```
  castor:helpers:acl access ignored for  +1s /-/v1/instances/
```

Then I tried to click again few minutes later and i got this: 
```
  castor:helpers:acl access ignored for  +326ms /-/v1/instances/
/home/kerphi/ezmaster/routes/route.js:173
          if(err) { throw err; }
                    ^

Error: HTTP code is 409 which indicates error: undefined - Conflict. The name "/inistcnrs-ezvis" is already in use by container 33b0ad45f5fa904f1d27f65b919a2c674d43b88cb5505d586e816e6c38153b76. You have to remove (or rename) that container to be able to reuse that name.

    at /home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:257:7)
    at Modem.buildPayload (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Makefile:11: recipe for target 'run-debug' failed
make: *** [run-debug] Error 1
```

So maybe it worked the first time but is it very slow ? and because there is no user feedback during the docker pull that's maybe the reason why i though it was not working.
