### ISSUE TITLE
crash when running make docker-run-debug

### ISSUE THREAD

**Issue by kerphi** [Inist-CNRS/ezmaster#6]
```
ezmaster_1     | /app/node_modules/castor-core/node_modules/mongodb/lib/utils.js:98
ezmaster_1     |     process.nextTick(function() { throw err; });
ezmaster_1     |                                   ^
ezmaster_1     | 
ezmaster_1     | TypeError: Cannot read property 'insertMany' of undefined
ezmaster_1     |     at /app/node_modules/castor-core/app/models/init.js:55:18
ezmaster_1     |     at Db.collection (/app/node_modules/castor-core/node_modules/mongodb/lib/db.js:452:27)
ezmaster_1     |     at db.collectionsIndex (/app/node_modules/castor-core/app/models/mongo.js:16:21)
ezmaster_1     |     at /app/node_modules/castor-core/app/models/init.js:54:34
ezmaster_1     |     at handleCallback (/app/node_modules/castor-core/node_modules/mongodb/lib/utils.js:96:12)
ezmaster_1     |     at /app/node_modules/castor-core/node_modules/mongodb/lib/db.js:470:40
ezmaster_1     |     at handleCallback (/app/node_modules/castor-core/node_modules/mongodb/lib/utils.js:96:12)
ezmaster_1     |     at /app/node_modules/castor-core/node_modules/mongodb/lib/cursor.js:835:16
ezmaster_1     |     at handleCallback (/app/node_modules/castor-core/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
ezmaster_1     |     at setCursorNotified (/app/node_modules/castor-core/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:490:3)
ezmaster_1     |     at /app/node_modules/castor-core/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:561:16
ezmaster_1     |     at queryCallback (/app/node_modules/castor-core/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
ezmaster_1     |     at Callbacks.emit (/app/node_modules/castor-core/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
ezmaster_1     |     at null.messageHandler (/app/node_modules/castor-core/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:295:23)
ezmaster_1     |     at Socket.<anonymous> (/app/node_modules/castor-core/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)
ezmaster_1     |     at emitOne (events.js:77:13)
```

**Comment by kerphi** [comment]
I'm unable to reproduce this bug. It is maybe related to the mongodb init step.
I close the issue cause too difficult to debug without a repeatable steps to reproduce the bug.
