### ISSUE TITLE
Crash clicking add instance btn but having localy the right docker image

### ISSUE THREAD

**Issue by kerphi** [Inist-CNRS/ezmaster#8]
I have the image localy:

```
[master] kerphi@p-gully:~/ezmaster
$ docker images | grep ezvis
inistcnrs/ezvis                    latest              a5af4af711a0        6 weeks ago         782.5 MB
```

Then I run ezmaster in debug mode:

```
[master] kerphi@p-gully:~/ezmaster
$ make run-debug
```

Then I visit the http://127.0.0.1:3000/ url

Then it crashes after few seconds with this error log:

```
  castor:helpers:acl access ignored for  +9s /-/v1/instances/
/home/kerphi/ezmaster/routes/route.js:173
          if(err) { throw err; }
                    ^

Error: HTTP code is 500 which indicates error: server error - Could not get container for mongo_db

    at /home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:257:7)
    at Modem.buildPayload (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/home/kerphi/ezmaster/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Makefile:11: recipe for target 'run-debug' failed
make: *** [run-debug] Error 1
```

**Comment by kerphi** [comment]
Another info: I used a local mongodb installed on the physical host (not using a docker container).

Maybe this is the reason because the ezvis container is tryng to link to a none existing mongodb container:

```
        docker.createContainer({Image: 'inistcnrs/ezvis:latest', name: 'inistcnrs-ezvis',
         'HostConfig': {
            'Links': ['mongo_db:mongo'],
```

**Comment by kerphi** [comment]
In order to make it simpler, maybe we should have a unique way to develop ezmaster. And maybe this way should be the most close as possible from the future production way to run ezmaster.
So maybe we should only develop using docker-compose to run ezmaster ?

So we could be sure a mongodb docker container exists and then we could link it securly to every ezmaster instances.
